changed logger to write to stdout if the log file is read only
salto-io/salto pull request #1517
Opened 2020-10-07 10:11 UTC by roironn

2020-10-07 15:29 UTC, netama approved these changes
LGTM. can you please add the ticket number to the title?

2020-10-07 15:29 UTC, netama commented on packages/logging/src/internal/log-file.ts
> +  } catch (err) {
nit: might be worth logging the error for debugging?

2020-10-07 15:47 UTC, royra requested changes
Sorry for butting in, but the loggers package should work on the browser - no fs. Also this is specific behavior for the client and belongs there.

2020-10-07 16:06 UTC, roironn commented
> Sorry for butting in, but the loggers package should work on the browser - no fs. Also this is specific behavior for the client and belongs there.

Then why does is natively support a SALTO_LOG_FILE env variable?

2020-10-07 16:21 UTC, roironn commented
> Sorry for butting in, but the loggers package should work on the browser - no fs. Also this is specific behavior for the client and belongs there.

Ahm...

https://github.com/salto-io/salto/blob/19b53505fd448d8d7f448082b29e4701b836d4e3/packages/logging/src/internal/pino.ts#L18

2020-10-07 16:51 UTC, royra commented
> > Sorry for butting in, but the loggers package should work on the browser - no fs. Also this is specific behavior for the client and belongs there.
> 
> Then why does is natively support a SALTO_LOG_FILE env variable?
> Ahm...
> 
> https://github.com/salto-io/salto/blob/19b53505fd448d8d7f448082b29e4701b836d4e3/packages/logging/src/internal/pino.ts#L18

Supporting fs is not like requiring it.
Looks like fs.createWriteStream is ported/mocked at the browser in CRA by chance.
Nonetheless the plain use of it looks like a bug in the logging module, so it's not a precedent for more bugs. 
I don't think you'll have such luck with stuff like `fs.accessSync`.

I think the other point re: separation of concerns is more important than the technical one. IMO `@salto-io/logging` should stand on its own regardless of its uses by core/saas. If core needs this specific behavior it can easily be implemented there.

2020-10-08 06:40 UTC, royra approved these changes
After v-f2f discussion: Approving, need to make sure it doesn't break saas ui.

2020-10-11 08:08 UTC, merged