SALTO-1236/netsuite file author information
salto-io/salto pull request #2457
Opened 2021-10-31 15:45 UTC by guyhamo

add author information to file and folder types

---

this is the last task in the author information feature for netsuite for a while so i will add here in the release notes and user notification for the feature supported elements

---
_Release Notes_: 

---
_User Notifications_:

2021-11-01 06:52 UTC, alonstern commented on packages/netsuite-adapter/src/filters/author_information/constants.ts
> +export const SYSTEM_NOTE_FILE_QUERY = 'SELECT systemnote.recordid, systemnote.name FROM systemnote WHERE systemnote.recordtypeid IS NULL AND EXISTS (SELECT file.id FROM file WHERE file.id = systemnot
Some points:
1. With this query you don't differ between `file` and `folder`, an internalid is unique only in the type level meaning that some files and folders might have the same internal id which can make you assign the modified by to the wrong instance. The good news is that you can differ files and folders by the "field" field. It seems like folders starts with `MEDIAITEMFOLDER` and files starts with `MEDIAITEM`

2. I don't think you need a separate query for that, it seems the results of this query are a subset of the results of the original query so you already have them

3. IIUC you can remove `files.ts` and in the original filter when you figure the type use also the `field` res value (which will save a bunch of duplicated code and queries)

2021-11-01 06:54 UTC, alonstern commented
> this is the last task in the author information feature for netsuite for a while so i will add here in the release notes and user notification for the feature supported elements

What about adding the internal ids of the SDF types to `TYPES_TO_INTERNAL_ID`

2021-11-01 12:12 UTC, guyhamo commented on packages/netsuite-adapter/src/filters/author_information/system_note.ts
> +    whereQuery += ' OR recordtypeid IS NULL'
looks good

2021-11-01 12:13 UTC, guyhamo commented on packages/netsuite-adapter/src/filters/author_information/system_note.ts
> +      if (isDefined(employeeId)) {
ok

2021-11-01 12:41 UTC, alonstern commented on packages/netsuite-adapter/src/data_elements/types.ts
> +  file: FILE_TYPE,
you can do in your filter 
```
import { TYPES_TO_INTERNAL_ID as  ORIGINAL_TYPES_TO_INTERNAL_ID } from '../../data_elements/types'

const TYPES_TO_INTERNAL ID = {
   ...ORIGINAL_TYPES_TO_INTERNAL_ID,
     // Might be worth to add a comment here
     file: FILE_TYPE,
     folder: FOLDER_TYPE,
}
```

2021-11-01 12:43 UTC, guyhamo commented on packages/netsuite-adapter/src/data_elements/types.ts
> +  file: FILE_TYPE,
agreed

2021-11-01 15:33 UTC, alonstern commented on packages/netsuite-adapter/src/filters/author_information/system_note.ts
> +  role: '-264',
This one should be in `TYPES_TO_INTERNAL_ID` (since it is the real id for role)

2021-11-01 15:33 UTC, alonstern approved these changes

2021-11-03 13:31 UTC, alonstern reviewed
.

2021-11-03 13:31 UTC, alonstern requested changes
.

2021-11-03 17:29 UTC, alonstern commented on packages/netsuite-adapter/src/data_elements/types.ts
> +  sdfinstallationscript: SCRIPT_TYPE,
To my knowledge, all the plugin types all have the `SCRIPT_TYPE`, can we also support them? (I guess we currently don't support them?)
e.g., `bankstatementparserplugin`, `customglplugin` (basically any sdf type with "plugin" in it)

2021-11-03 17:29 UTC, alonstern commented on packages/netsuite-adapter/src/data_elements/types.ts
> +  customsegment: FIELD_TYPE,
can you make sure it works for `customsegment`? it's a type with a pretty weird behavior with its internal id and I want to make sure we get the right internal id

2021-11-04 11:01 UTC, alonstern approved these changes

2021-11-04 13:33 UTC, merged