[SALTO-2601] Jira template filter
salto-io/salto pull request #3288
Opened 2022-08-23 20:07 UTC by yanaise

Process some smart values in jira as templates referencing field instances

---

See ticket

---
_Release Notes_: 
[Jira]
Parse smart values under automations as template values, that include references to the instances of the fields that the smart value references.
 
---
_User Notifications_: 
[Jira]
Some value fields under Automation components will change. Instead of containing the old text, they will contain templates, which are a mix of references to the referenced fields, and the text around the referenced fields.

2022-08-24 20:24 UTC, netama reviewed
looks thorough :) only did a first pass, but added some comments. I have a feeling we might need to be a little more careful around how we look up fields (+ added some comments around readability and async)

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +const issueFieldNameToTypeMapping: Record<string, string> = {
can you please add comments explaining these? (specifically on the second I think you mentioned it is only needed for standard types)

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +  'Story Points estimate': 'Story Points estimate',
I'm a little surprised that both sides can have spaces - what's the explanation?

EDIT: saw below that we are checking the actual field names returned from jira - I suspect we might not be able to assume these always have exactly the same case, but will leave it to @alonstern to comment

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +  fieldsByName: Record<string, InstanceElement>): TemplateExpression | string => {
readability nit
```suggestion
const stringToTemplate = (
  referenceSt: string,
  fieldsByName: Record<string, InstanceElement>,
): TemplateExpression | string => {
```
or
```suggestion
const stringToTemplate = (
  referenceSt: string, fieldsByName: Record<string, InstanceElement>,
): TemplateExpression | string => {
```

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +    })
readability nit
```suggestion
  return extractTemplate(
    referenceSt,
    [REFERENCE_MARKER_REGEX],
    expression => {
      const jiraReference = expression.match(simpleIssueRegex)
      if (jiraReference) {
        return handleJiraReference(expression, jiraReference)
      }
      return expression
    },
  )
```

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +        i.value.name);
1. readability
```suggestion
  const fieldsByName = _.keyBy(
    instances.filter(i => i.elemID.typeName === 'Field' && _.isString(i.value.name)),
    (i: InstanceElement): string => i.value.name
  );
```
2. I don't think we can assume fields are unique by their name in jira... do we have other ways to filter these to make sure we are adding a reference to the right one? @alonstern please chime in if you have more context on this :)

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +    log.error(`Error parsing templates in deployment: ${e.message}`)
I'm wondering if the call stack might be useful here as well? wdyt?

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +    ?? part.value.value.name) : '')}`
this is not very readable :) both because of where the line breaks are, and because we have relatively complex logic inside the string template. can we maybe pre-calculate a constant with a meaningful name and then use it in the string?

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +    onFetch: async (elements: Element[]): Promise<void> => log.time(async () =>
why do we need the full function signatures here? (also applies for `preDeploy` and `onDeploy`)

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +      replaceFormulasWithTemplates(elements.filter(isInstanceElement)), 'Create template creation filter'),
nit: what's the meaning of `Create` here?

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +        (getAutomations(await awu(changes).map(getChangeData).toArray())).forEach(
are you sure this is running as intended? I might be missing something but it looks to me like we are returning without waiting for the `forEach` functions to return.

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +        log.error(`Error parsing templates in deployment: ${e.message}`)
same re stack trace

2022-08-24 20:24 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +      (getAutomations(await awu(changes).map(getChangeData).toArray())).forEach(
same re async

2022-08-24 21:20 UTC, yanaise commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +        i.value.name);
2. Apparently it's possible. Also from trying it and fetching it looks like the current adapter doesn't really handle this scenario. I'm not sure what the right behavior is.

2022-08-25 11:15 UTC, alonstern approved these changes
🔥 🚀

2022-08-25 11:15 UTC, alonstern commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +      } catch (e) {
What is going to happen in deploy when this happens? I am afraid we will resolve the references in the automation wrong and mess up the automation in the deployment. Probably would be better the throw an error at this stage

2022-08-25 11:15 UTC, alonstern commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +                Object.keys(component.value).forEach(k => {
nit: I think the code will be a little more readable if you replace the k and all the other one letter variables with the full name, in this case `key`

2022-08-25 11:15 UTC, alonstern commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +)
nit:
```suggestion
const issueTypeNameToFieldMapping = _.invert(issueFieldNameToTypeMapping)
```

2022-08-25 11:15 UTC, alonstern commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +      } catch (e) {
I am not sure if we fail to resolve the references back we would want to hide it from the user, otherwise it will just override the references in his workspace

2022-08-25 11:15 UTC, alonstern commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +        return new ReferenceExpression(elem.elemID, elem)
I think if the reference is by the name of the field we would want the reference to point to the field name and not the field instance (@netama correct me if you think we shouldn't do that here)

2022-08-25 11:15 UTC, alonstern commented on packages/jira-adapter/src/adapter.ts
> +  handleTemplateExpressionsFilter,
We will have other template expressions in the future that probably won't be handled by this filter. Maybe we should call it something like `smartValuesReferencesFilter`?

2022-08-25 11:16 UTC, alonstern requested changes
🔥 🚀 (accidentally approved before)

2022-08-25 13:57 UTC, yanaise commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +    log.error(`Error parsing templates in fetch: ${e.message}`, e)
I don't know because whatever error we see here is completely unexpected, there's no action we do here that should have a failure possibility. So I feel like that's an inconsistent state and it's better to just get out

2022-08-25 14:04 UTC, netama commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +        return new ReferenceExpression(elem.elemID, elem)
:+1: assuming this falls under the bucket you mentioned of references that would need to change on field rename

2022-08-25 18:01 UTC, yanaise commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +const issueFieldNameToTypeMapping: Record<string, string> = {
Mmm, I'm not sure how you mean "get it from the elements".
When someone writes issue.duedate, that maps on to an element that has the name "Due Date". When someone writes "issue.Story Points", that maps on to an element with the name "Story points". 
So I'm looking at both of these elements, what kind of deduction function can I use to know what value would point at them?

2022-08-25 18:15 UTC, yanaise commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +        return new ReferenceExpression(elem.elemID, elem)
mmm, we could do that, but that's not what we did with Zendesk and:
A. I think it makes sense because this isn't really referring to the name property of the field, it's just invoking the field, and using the name to get to it. I think semantically it is pointing at the field, not its name. You can see this from more complicated smart values that do point to specific attributes under some field. Arguably it would be confusing in the nacl.
B. I think something in the template implementation in Zendesk motivated us to choose the whole instance rather than the field, but sadly I don't remember what. Maybe it's something in the deploy plan. I could look further into it if you're not convinced by A.

2022-08-28 05:44 UTC, alonstern commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +const issueFieldNameToTypeMapping: Record<string, string> = {
IIUC you can do something like
```
issueFieldNameToTypeMapping  = Object.fromEntries(elements
  .filter(isInstanceElement)
  .filter(instance => instance.elemID.typeName === FIELD_TYPE_NAME)
  // This is to check that the field is a system field, only system field has the schema value)
  .filter(instance => instance.value.schema !== undefined)
  .map(instance => [instance.value.id, instance.value.name]))
```

`Story Points` and `Story Points estimate` are custom fields. IIUC they don't really need to be part of this list and it will work just the same if you remove them

2022-08-28 05:44 UTC, alonstern commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +        return new ReferenceExpression(elem.elemID, elem)
Some more context about this decision: we saw several places in Jira where Jira internally depends on the field name, this means that if a user changes a field name (either with Salto or in the Jira UI), all the places that depend on its name will break. By adding the `name` to the reference, when changing the name, Core will be able to know to add the elements which depend on the name to the deployment plan and prevents them from breaking. 

So we decided to add the `name` to the reference wherever in Jira the reference is internally by name.

2022-08-28 05:44 UTC, alonstern commented on packages/jira-adapter/src/filters/automation/handle_template_expressions.ts
> +    log.error(`Error parsing templates in fetch: ${e.message}`, e)
I feel it is more inconsistent to put it here because when there is a problematic instance, you will parse all the instances until we get to it which depends on the order of the elements which isn't guaranteed to be the same in each run

2022-08-29 11:23 UTC, alonstern commented
Could you add support for also creating the reference in smart values with inner properties `issue.[Custom Field].id -> issue.${jira.Field.instance.CustomField.name}.id` (as mentioned in https://salto-io.atlassian.net/browse/SALTO-2639)

2022-08-30 12:57 UTC, alonstern commented
The fixes look good 👌 👌
I just found out that in the value `{{issue.<value>}}` you can put either and id of a field or the name of the field and there's actually no difference between system and custom fields in that area. This means that we currently won't support system field references that use the name or custom fields that use the id (I saw Mynd have some).
Could you please add support for those cases and when the reference is by id use the top level elem id as the reference and when the reference is by name add `.name` to the reference path

2022-09-07 13:54 UTC, closed without merging