salto-2883 netsuite partial fetch
salto-io/salto pull request #3953
Opened 2023-02-12 14:27 UTC by kami-delaroz

return a list of supported types for NetSuite partial fetch., in order to support autocomplete and "fetch all" in quick fetch.
(extra work in SaaS has to be done in order to support this)

---

_Additional context for reviewer_
None
---
_Release Notes_: 
When choosing partial fetch in NetSuite, a list of supported types will be shown, allowing autocomplete and easy configuration

---
_User Notifications_: 
_None_

2023-02-12 20:06 UTC, omrilit approved these changes
Looks good!

2023-02-12 20:06 UTC, omrilit commented on packages/netsuite-adapter/src/data_elements/types.ts
> +export const SUPPORTED_TYPES = Object.keys(TYPE_TO_IDENTIFIER)
Could you please explain this one?

2023-02-12 20:06 UTC, omrilit commented on packages/netsuite-adapter/src/config.ts
> +        [CORE_ANNOTATIONS.RESTRICTION]: createRestriction({ values: [
I see that we have the below already defined in https://github.com/salto-io/salto/blob/main/packages/netsuite-adapter/src/query.ts#L162.
Maybe we can reuse it so if one changes the other one will get changed too?

2023-02-12 20:07 UTC, omrilit requested changes
It was approved mistakenly 😲

2023-02-14 11:50 UTC, kami-delaroz commented on packages/netsuite-adapter/src/config.ts
> +        enforce_value: false }), // in order to support specific custom record types
Yes, I'll remove it

2023-02-14 11:52 UTC, kami-delaroz commented on packages/netsuite-adapter/src/data_elements/types.ts
> +export const SUPPORTED_TYPES = Object.keys(TYPE_TO_IDENTIFIER)
After revisiting this area with @dantal4 , looks like the TYPE_TO_IDENTIFIER should be used (also in the origin usage), as this map contains the relevant supported types. TYPES_TO_INTERNAL_ID contains some duplications and irrelevant types

2023-02-14 13:53 UTC, omrilit approved these changes
Great work!

2023-02-14 15:35 UTC, merged