SAAS-6953 add quickFetch to adapter-api and make Netsuite implementing it
salto-io/salto pull request #3963
Opened 2023-02-14 13:25 UTC by omrifarkash

As part of https://salto-io.atlassian.net/browse/SAAS-6953?focusedCommentId=67080&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-67080
In this PR:
- Adding a new function to adapter-api 'quickFetch' this function is not mandatory and each adapter can implement it or not.
- Make Netsuite adapter to implement quickFetch, with the same logic that it has done with 'useChangesDetection' from the config file.

Note, for now I didn't remove 'useChangesDetection' from the config, since I want to support the old way to run quick fetch
 
---

---
_Release Notes_: 
None
---
_User Notifications_: 
None

2023-02-15 06:30 UTC, dantal4 approved these changes
💯

2023-02-15 06:30 UTC, dantal4 commented on packages/netsuite-adapter/src/adapter.ts
> +  private readonly useChangesDetection: boolean // TODO remove this from configuration
can you add that TODO comment in config.ts too?

2023-02-15 09:54 UTC, dantal4 requested changes
Please validate with @adamro / @netama  regarding the core API change 🙏

2023-02-15 10:11 UTC, omrilit reviewed
Great work!

2023-02-15 10:11 UTC, omrilit commented on packages/netsuite-adapter/src/adapter.ts
> +  private readonly useChangesDetection: boolean // TODO remove this from configuration
Please write in the TODO the relevant ticket and consider to open a dedicated ticket

2023-02-15 10:11 UTC, omrilit commented on packages/core/src/api.ts
> +  runQuickFetch?,
I think that we agreed on naming it "useChangeDetection" or something similar or something similar, WDYT?

2023-02-15 10:11 UTC, omrilit commented on packages/adapter-api/src/adapter.ts
> +  quickFetch?: (opts: FetchOptions) => Promise<FetchResult>
I am not sure we'd like to name it quickFetch also in the adapter-api layer. @netama @adamro WDYT?

2023-02-15 10:11 UTC, omrilit commented on packages/core/src/core/fetch.ts
> +          const fetchResult = await fetchFunction({
With this implementation, in case you have an env with multi adapters, e.g. NS & Jira you'll trigger a fetch for NS and will throw an error for Jira.
I think that it's better to catch this situation in advance and avoid initiating fetch for adapters that do support the change-detection based fetch.

2023-02-15 10:16 UTC, adamro commented on packages/core/src/core/fetch.ts
> +            throw new Error(`Adapter ${accountName} is not support quick fetch operation`)
@rozenmanofer 
Can you please with reviewing this text? Something doesn't work for me with the English 

@omrifarkash notice you only used the accountName and not the adapterName and it's not the account that doesn't support quick fetch, it's the adapter

2023-02-15 10:16 UTC, adamro commented on packages/core/src/core/fetch.ts
> +          if (!fetchFunction) {
If you have more than one adapter that doesn't support quick fetch you will fail on the first one. We need to decide if it's OK or we need to aggregate the failures to give maximum information

2023-02-15 10:16 UTC, adamro commented on packages/adapter-api/src/adapter.ts
> +  quickFetch?: (opts: FetchOptions) => Promise<FetchResult>
Did we agree to call this new operation `quickFetch`? I thought we spoke about `withChangesDetectionFetch` or something down that line cause quick doesn't necessary describe it

2023-02-15 10:33 UTC, omrifarkash commented on packages/core/src/core/fetch.ts
> +          const fetchResult = await fetchFunction({
@omrilit 
I agree, this should never happen.
I will add an api to core that given accounts name it return wether all support quickFetch. when a client call core fetch with runQuickFetch flag with some adapters, it is his responsibility to check that all adapters are support quick fetch by using the new api.
WDYT?

Please note that in validation case we do the same, if core is running deploy with checkOnly flag on not supported adapter, it throws an error. (Unfortunately for validation case we don't have an api to check wether adapter supports validation. We hold an hard coded information about that)

2023-02-15 10:36 UTC, omrifarkash commented on packages/core/src/core/fetch.ts
> +            throw new Error(`Adapter ${accountName} is not support quick fetch operation`)
@adamro I had that feeling, how do I get the adapter name?

These are the properties I have in adapter
![image](https://user-images.githubusercontent.com/63018798/219003707-1e40a96a-c60d-4d45-843e-4c2b6f981fb2.png)

2023-02-15 10:37 UTC, omrilit commented on packages/core/src/core/fetch.ts
> +          const fetchResult = await fetchFunction({
I don't think that a new core API is needed for it.
I would just do the validation in the same function but will raise an error for all adapters that do not support "quick fetch" together and not trigger a fetch for the others.

2023-02-15 10:41 UTC, omrifarkash commented on packages/core/src/core/fetch.ts
> +          if (!fetchFunction) {
@adamro  Good point, I think another interesting question here is the case where we have a supported adapter and unsupported one. 
The first will run fetch and the second will throw an error, what are the results in this case?

I'm starting to think I better check that all adapters support quickFetch before this iteration WDYT?

2023-02-15 10:42 UTC, omrifarkash commented on packages/adapter-api/src/adapter.ts
> +  quickFetch?: (opts: FetchOptions) => Promise<FetchResult>
Doesn't sound like an operation name to me, but I don't have a strong opinion here.
@omrilit @netama  ?

2023-02-15 10:44 UTC, omrifarkash commented on packages/core/src/api.ts
> +  runQuickFetch?,
I think it depends on the name we will decide in `AdapterOperations`

As long as it is 'quickFetch' there I think 'runQuickFetch' is a fine name for the flag

2023-02-15 11:03 UTC, adamro commented on packages/core/src/core/fetch.ts
> +            throw new Error(`Adapter ${accountName} is not support quick fetch operation`)
Notice you also have `accountToServiceNameMap` in the context, that holds the "adapter name" aka "service name" which is what you need in this context

2023-02-15 12:04 UTC, omrifarkash commented on packages/core/src/core/fetch.ts
> +          const fetchResult = await fetchFunction({
@omrilit  Ok, but still we need the new api. We do not want to send a fetch request with quickFetch flag to unsupported adapters and fail on runtime.
We need the ability to check wether all current adapters support quick fetch or not, (UI can be a client of this api), don't you agree?

2023-02-15 12:15 UTC, omrilit commented on packages/core/src/core/fetch.ts
> +          const fetchResult = await fetchFunction({
@adamro @netama WDYT here? I understand @omrifarkash point, but I think that for simplicity reasons we decided to modify it so the UI will have it hard coded and we won't expose it using the code from the OSS, right?

2023-02-15 12:26 UTC, adamro commented on packages/core/src/core/fetch.ts
> +          if (!fetchFunction) {
In the case you presented the result will be possibly some waste of time and an error thrown :) 

You can partition the adapters by wether there's a proper fetch function to run or not before the Promise.all and throw an error with the information about all the ones that don't [if they exist]
(and if they don't exist run the Promise.all on the ones with a legit fn)

2023-02-15 13:42 UTC, adamro commented on packages/core/src/core/fetch.ts
> +      .filter(([, fetchFunction]) => isUndefined(fetchFunction))
We prefer usage is `isDefined` from `lowerdash`

2023-02-16 10:30 UTC, netama reviewed
looks good, but I think we can simplify the implementation a bit - added some comments (most are nits)

2023-02-16 10:30 UTC, netama commented on packages/core/src/api.ts
> +  withChangeDetection?: boolean,
not related to this PR specifically, but we should switch these to named parameters before it's too late cc @adamro , I'll create a ticket

2023-02-16 10:30 UTC, netama commented on packages/core/src/api.ts
> +  ChangeDetection?,
args should start with lowercase
```suggestion
  changeDetection?,
```

2023-02-16 10:30 UTC, netama commented on packages/core/src/core/fetch.ts
> +      .filter(([, fetchFunction]) => !isDefined(fetchFunction))
nit: can we just use `fetchFunction === undefined`?

2023-02-16 10:30 UTC, netama commented on packages/core/src/core/fetch.ts
> +    const adaptersWithoutFetchFunction = Object.entries(accountNameToFetchFunction)
1. this can have duplicate adapter names if there is more than one account from the same adapter
2. a bit of a nit, but I think the code can be simplified if we only get into the flow of calculating `adaptersWithoutFetchFunction` if `withChangeDetection` is true - because right now `accountNameToFetchFunction` masks some flow paths that don't have to overlap (meaning, we can either replace the `pickBy` below with `<>.fetchWithChangeDetection ?? <>.fetch`, or avoid it completely by using stricter type checks)

2023-02-16 10:30 UTC, netama commented on packages/core/src/core/fetch.ts
> +      throw new Error(`${adaptersWithoutFetchFunction.join(', ')} adapters do not support quick fetch operation`)
nits: 
1. I think we can make this more informative by keeping the account names, so the user knows which accounts are problematic and not only which adapters
2. for the current phrasing - I think it would make more sense if it's `Adapters <...>` and not `<...>` adapters`
3. if the term we used is `withChangeDetection`, shouldn't we use it here as well? I don't think the users were introduced to the term "quick fetch"

2023-02-16 10:46 UTC, omrifarkash commented on packages/core/src/api.ts
> +  ChangeDetection?,
good catch, should have been `withChangeDetection`

2023-02-16 10:49 UTC, omrifarkash commented on packages/core/src/core/fetch.ts
> +    const adaptersWithoutFetchFunction = Object.entries(accountNameToFetchFunction)
1. I don't think I fully understood your concern here, the map is between the accountName to its adapter fetch function. The duplication can be in the fetchFunction, but it still the same behavior as it was before this change.

2. No strong opinion here, personally I prefer the current style but I don't mind changing it to your suggestion

2023-02-16 10:50 UTC, omrifarkash commented on packages/core/src/core/fetch.ts
> +          const fetchResult = await fetchFunction({
@netama Thanks for your comments.
Could you please share your opinion on this discussion as well?

2023-02-16 11:46 UTC, omrifarkash commented on packages/core/src/core/fetch.ts
> +      throw new Error(`${adaptersWithoutFetchFunction.join(', ')} adapters do not support quick fetch operation`)
Re 1. do you think we should add both accountName and adapterName to the error message?

2023-02-16 14:01 UTC, netama commented on packages/core/src/core/fetch.ts
> +          const fetchResult = await fetchFunction({
oops sorry.
I think eventually we should have this API (for adapter "capabilities" in general) - extending @alonstern 's suggestion on https://salto-io.atlassian.net/browse/SALTO-1589.
I think that for now we should follow the pattern we're using today for `checkOnly` / `deployOrValidate` in the OSS (so I agree with @omrilit that we can probably wait a bit longer with defining the additional API - though I agree it will be useful eventually). 
re the knowledge in the SAAS - if we already have these conditions elsewhere (I think we do for the deploy-or-validate flow?), I think we can keep them here for now and discuss when @ori-moisis is back

2023-02-16 14:02 UTC, netama commented on packages/core/src/core/fetch.ts
> +      throw new Error(`${adaptersWithoutFetchFunction.join(', ')} adapters do not support quick fetch operation`)
re 1 - I do, but this is a nit so up to you

2023-02-16 14:03 UTC, netama commented on packages/core/src/core/fetch.ts
> +    const adaptersWithoutFetchFunction = Object.entries(accountNameToFetchFunction)
re 1 - what happens if you have two salesforce connections? won't we print `Adapters: salesforce, salesforce`? (didn't run it so maybe I'm missing something, but this is what it looked like to me)

2023-02-19 09:35 UTC, dantal4 commented on packages/netsuite-adapter/src/adapter.ts
> +      isPartial,
this var should be used in here too - https://github.com/salto-io/salto/pull/3963/files#diff-ab4d4c0f4c556dc581b77c83dcfd62d7952c7cd140847413c41da0d498fa8dd9R252

2023-02-20 07:42 UTC, netama approved these changes
LGTM 🎈  assuming @dantal4 / @omrilit / @adamro approve, with one remaining comment re linking only to OSS tickets.
I think we can add release notes for this, e.g. something like
> _Core_:
> * Allow adapters to expose a `fetchWithChangeDetection` function that only fetches changes since the last fetch
> 
> _Netsuite adapter_:
> * Implement `fetchWithChangeDetection` to allow fetching only changes since the last fetch

(I'm sure the phrasing can be better)

2023-02-20 07:42 UTC, netama commented on packages/core/src/api.ts
> +  withChangeDetection?: boolean,
added https://salto-io.atlassian.net/browse/SALTO-3675

2023-02-20 07:42 UTC, netama commented on packages/netsuite-adapter/src/adapter.ts
> +  private readonly useChangesDetection: boolean // TODO remove this from configuration https://salto-io.atlassian.net/browse/SAAS-6953
we shouldn't link to SAAS tickets from the OSS, please add an OSS ticket (and this can just mention SALTO-XXXX )

2023-02-20 08:58 UTC, dantal4 approved these changes
💯 On the NS side

2023-02-20 08:59 UTC, merged