SALTO-3986: Support Brand Email template
salto-io/salto pull request #6559
Opened 2024-09-14 18:55 UTC by shir-reifenberg

Added support for email customizations

---

_Additional context for reviewer_

- Each brand has a fixed type of `EmailTemplate` instances, for each type of email ("forget password", "user activation", etc). The email templates are auto created when the brand is added (similar to brand theme)
- For each type of email, Okta allows customizing it in different languages.
- Planned to add E2E, but our E2E account doesn't allow customizations. Will update tests in `adapter.test.ts` soon.

---
_Release Notes_: 

_Okta adapter_:
- Add support in Email Templates for Brands

---
_User Notifications_: 

_Okta adapter_:
- `EmailCustomization` and `EmailTemplate` elements will be added for workspaces with brands customizations.

2024-09-15 08:33 UTC, Nurdok requested changes
Looks great! That was really fast!

2024-09-15 08:33 UTC, Nurdok commented on packages/okta-adapter/src/definitions/deploy/deploy.ts
> +          remove: [{ request: { earlySuccess: true } }],
In other types that are automatically removed (`ProfileMapping`, `BrandTheme`) we perform a GET to make sure that the instance was deleted. Should we do this here, too?

2024-09-15 08:33 UTC, Nurdok commented on packages/okta-adapter/src/definitions/deploy/deploy.ts
> +    EmailCustomization: {
Please put this in a `const` too.

2024-09-15 08:33 UTC, Nurdok commented on packages/okta-adapter/src/definitions/fetch/fetch.ts
> +          rename: [{ from: '_embedded.settings', to: 'settings', onConflict: 'override' }],
nice

2024-09-15 08:33 UTC, Nurdok commented on packages/okta-adapter/e2e_test/adapter.test.ts
Please also add some HTTP-recording tests (the other `adapter.test.ts` 😄)

2024-09-15 20:01 UTC, shir-reifenberg commented on packages/okta-adapter/src/definitions/deploy/deploy.ts
> +          remove: [{ request: { earlySuccess: true } }],
true, wanted to implement it with `additionalStatusCode` but I think there's might be an issue with it (opened SALTO-6664), I think we can start like this and adjust once fixed

2024-09-15 20:03 UTC, shir-reifenberg commented on packages/okta-adapter/e2e_test/adapter.test.ts
Added 😄 seems like i'm doing something wrong cause the entire thing fails in my added tests, let's discuss tomorrow IRL

2024-09-16 14:11 UTC, Nurdok approved these changes

2024-09-17 05:07 UTC, merged