[WIP] Custom Role support in Okta
salto-io/salto pull request #6933
Opened 2024-12-11 16:06 UTC by shir-reifenberg

_Replace me with a description of the changes in this PR_

---

_Additional context for reviewer_

---
_Release Notes_: 
_Replace me with a short sentence that describes the effect of this change on Salto users_

---
_User Notifications_: 
_Replace me with a short sentence that describes changes that will appear in NaCls and are not caused by user actions (e.g. a new annotation, field values that are converted to references, etc). Hidden changes should not be listed._

2024-12-11 16:54 UTC, shir-reifenberg commented on packages/okta-adapter/src/definitions/deploy/types/roles.ts
> +      // naclCase permission labal because the label includes dots
fix type `labal`

2024-12-18 08:08 UTC, Nurdok requested changes

2024-12-18 08:08 UTC, Nurdok commented on packages/okta-adapter/src/definitions/deploy/types/roles.ts
> +      _.set(sharedContext, naclCase(permission.label), true)
I _think_ this is wrong because the shared context is the same for all request, and there's no keying by the role ID here, so when you look for a permission later, you'll see `true` on permission from _all_ roles. Did you try deploying two distinct roles with different permissions in the same deployment?

I think you should either:
1. Key permission labels under the role ID here, and when reading in the permission request.
2. In this function, only flatten the permission array and don't save to the shared context. Rename to, e.g., `flattenPermissionArray`. Then use `copyFromResponse.toSharedContext`, set it to `pick: 'permissions'` and set `nestUnderElemID` to `true` (this will only work if the response contains the permissions, which IIUC it does). It'll be a bit clearer to read directly from the definitions.
3. Only flatten here and rename like above, but don't use the shared context at all, rather use the element source in the permission request to figure out which permissions have conditions.

I think the last option is best because using the shared context between requests is harder to read and understand - it requires cooperation between two seemingly unrelated functions and is more prone to errors if you're not careful about using the same keying logic, etc.

2024-12-18 08:08 UTC, Nurdok commented on packages/okta-adapter/src/definitions/deploy/deploy.ts
> +    [ROLE_TYPE_NAME]: {
Can you please add an HTTP-recording test for the new supported actions (the other `adapter.test.ts`)?

2024-12-18 10:47 UTC, shir-reifenberg commented on packages/okta-adapter/src/definitions/deploy/types/roles.ts
> +      _.set(sharedContext, naclCase(permission.label), true)
Good catch! thank you
I think I didn't encountered this as each element is on a different change group, and we didn't fixed sharedContext to share info between groups..
I'll see what's goes best with the deployment order and will make the adjustments 🤞 (though I kind of prefer avoiding the element source as I have the parent change in hand..)

2024-12-19 15:09 UTC, Nurdok approved these changes

2024-12-19 15:09 UTC, Nurdok commented on packages/okta-adapter/src/definitions/fetch/fetch.ts
> +        AppProvisioning: {
Remove :)

2024-12-19 15:47 UTC, merged